### ISSUE TITLE
Problem with System::file().getBaseName

### ISSUE THREAD

**Issue by klugem** [GATB/leon#1]
If a filename contains multiple '.' the decoding will fail because System::file().getBaseName returns only the first part of the filename.

Example: leon -file C2448.21.fastq.leon -d -lossless

Start decompression
    Input filename: C2448.21.fastq.leon
    Qual filename: ./C2448.fastq.qual
    Output format: Fastq
    Kmer size: 31

```
Input File was compressed with leon version 1.0.0
Block count: 3
```

[Decompressing all streams]  100  %   elapsed:   0 min 0  sec    estimated remaining:   0 min 0  sec

```
Output filename: ./C2448.fastq.d
Time: 0.79s
Speed: 0.00 mo/s
```

--> It does only extract the first three sequences without qualities but does not report any error!
--> Check, if .qual file is there if --lossless if given!

**Comment by rizkg** [comment]
Hi, sorry for late answer.
This bug has been fixed. Please checkout latest sources and tell me if you still encounter a problem.
