### ISSUE TITLE
try to compress hg19.fa

### ISSUE THREAD

**Issue by dridk** [GATB/leon#4]
I have just tried leon by compressing hg19.fa. 

```
 leon -file hg19.fa -c  
```

I guess I get an error. 

```
[DSK: nb solid kmers found : 35010472    ]  100  %   elapsed:   3 min 37 sec   remaining:   0 min 0  sec   cpu: 185.8 %   mem: [  38, 3[DSK: nb solid kmers found : 35010472    ]  100  %   elapsed:   3 min 37 sec   remaining:   0 min 0  sec   cpu: 185.8 %   mem: [  38, 3[DSK: nb solid kmers found : 35010472    ]  100  %   elapsed:   3 min 37 sec   remaining:   0 min 0  sec   cpu: 185.8 %   mem: [  38, 3[DSK: nb solid kmers found : 35010472    ]  100  %   elapsed:   3 min 37 sec   remaining:   0 min 0  sec   cpu: 185.8 %   mem: [  38, 3626, 4201] MB 
[Compressing headers                     ]  100  %   elapsed:   0 min 17 sec   remaining:   0 min 0  sec
        End header compression
                Headers size: 1193
                Headers compressed size: 604
                Compression rate: 0.5063
Abundance threshold: 4 (auto)    (nb solid kmers: 22647208)
[fill bloom filter                       ]  100  %   elapsed:   0 min 6  sec   remaining:   0 min 0  sec
[Compressing dna                         ]  100  %   elapsed:   0 min 11 sec   remaining:   0 min 0  sec
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
[1]    30874 abort (core dumped)  leon -file hg19.fa -c
```

I was not able to extract the leon file, wich is probably corrupted. It's only 604 bytes. 
I will test on a stronger computer to see if it is better.

**Comment by dridk** [comment]
May it come from the presence of N in the sequence ?

**Comment by clemaitre** [comment]
Hi,

What does your input file contain ? It seems from your command line and the output that this is  genomic sequences (human genome), is it ?
leon is designed to compress files of sequencing reads, therefore it expects numerous and short sequences with lots of redundancy (from the depth of coverage). It can not compress genome sequences. 

Claire

**Comment by dridk** [comment]
Ok, Thanks for your reply. That what I thought. The title makes me think it's a compression algorithm for all kind of fasta file.  
You should mention in the readme the maximum length of read supported by leon. And show a message error if read length exceed the maximum.
